pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('signin/', views.signin, name="signin"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('<int:user_pk>/update/', views.update, name="update"),
    path('<int:user_pk>/delete/', views.delete, name="delete"),
    path('<int:user_pk>/follow/', views.follow, name="follow"),
]

pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('menu/', views.menu),
    path('accounts/', include("accounts.urls")),
    path('behinds/', include("behinds.urls")),
    path('movies/', include("movies.urls")),
    path('mypage/', include("mypage.urls")),
    path('recommendations/', include("recommendations.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjt/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
  {% block css %}
  {% endblock css %}
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
</head>
<body>
  <div id="navbar-box">
    <div id="navbar">
      <a href="#" class="menu-bars" id="show-menu">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <nav id="nav-menu">
      <ul class="nav-menu-items">
        <div id="navbar-toggle">
          {% comment %} <a href="#"><h1>Dojiny</h1></a> {% endcomment %}
          <a href="#" class="menu-bars" id="hide-menu">
            <i class="fas fa-bars nav-icons"></i>
          </a>
        </div>
        <hr class="nav-hr">
        <div class="nav-sections">
          <li class="nav-text"><img src="{{ user.profile_image.url }}" alt="profile" class="modal-user"></li>        
          <li class="nav-text user-name">{{ user.username }}</li>        
          <li class="logout"><a href="{% url 'accounts:logout' %}">로그아웃</a></li>        
          <br>
          <li class="nav-text item"><a href="http://127.0.0.1:8000/movies/">전체 영화</a></li>        
          <br>
          <li class="nav-text item"><a href="http://127.0.0.1:8000/behinds/">감독 비하인드</a></li>        
          <br>
          <li class="nav-text item"><a href="http://127.0.0.1:8000/recommendations/{{ user.pk }}/rec/">추천 영화</a></li>        
          <br>
          <li class="nav-text item"><a href="http://127.0.0.1:8000/mypage/{{ user.pk }}/profile/">마이페이지</a></li>
        </div>
      </ul>
    </nav>
  </div>



  {% block content %}
  
  {% endblock content %}
  {% block script %}
  
  {% endblock script %}
  <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
  <script src="https://kit.fontawesome.com/13854dfe88.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>

pjt/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
  <div class="box">
    <img src="{% static 'images/spiderman.jpg' %}" alt="">
    <div class="title">With great power comes great responsibility.</div>
    <div class="login">
      {% comment %} <a href="{% url 'accounts:signup' %}">SIGN UP</a> |
      <a href="{% url 'accounts:signin' %}">SIGN IN</a> {% endcomment %}
      <a href="{% url 'accounts:signup' %}">LOG IN</a>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit">LOG OUT</button>
      </form>
    </div>
  </div>
</body>
</html>

pjt/templates/menu.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/menu.css' %}">
</head>
<body>
  <div class="box">
    <div class="image-box" onclick='moviesPage()'>
      <div class="img-1 imgs">
        <div class="span-m">
          <span>전</span><br>
          <span>체</span><br>
          <br>
          <span>영</span><br>
          <span>화</span><br>
          <br>
        </div>
      </div>
      <div class="hidden">이 공간은 모든 영화를<br> 만나볼 수 있는 공간입니다.</div>
    </div>
    <div class="image-box" onclick='behindPage()'>
      <div class="img-2 imgs">
        <div class="span-m">
          <span>감</span><br>
          <span>독</span><br>
          <span>비</span><br>
          <span>하</span><br>
          <span>인</span><br>
          <span>드</span>
        </div>
      </div>
      <div class="hidden">이 공간은 영화 감독들의<br> 이야기를 만나볼 수 있는<br> 공간입니다.</div>
    </div>
    <div class="image-box" onclick='recommendationPage()'>
      <div class="img-3 imgs">
        <div class="span-m">
          <span>추</span><br>
          <span>천</span><br>
          <span>영</span><br>
          <span>화</span><br>
          <br>
          <br>
        </div>
      </div>
      <div class="hidden">이 공간은 평가한 영화의<br> 장르와 별점을 기반으로<br> 추천 영화를 만나볼 수 있는<br> 공간입니다.</div>
    </div>
    <div class="image-box" onclick='myPage()'>
      <div class="img-4 imgs">
        <div class="span-m">
          <span>마</span><br>
          <span>이</span><br>
          <span>페</span><br>
          <span>이</span><br>
          <span>지</span><br>
          <br>
          <span style="display:none;" id="userid">{{ user.pk }}</span>
        </div>
      </div>
      <div class="hidden">이 공간은 나를 만나볼 수 있는 공간입니다.</div>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/menu.js' %}"></script>
</body>
</html>