pjt/behinds/urls.py
from django.urls import path
from . import views

app_name = "behinds"

urlpatterns = [
     path('', views.index, name="index"),
     path('create/', views.create, name="create"),
     path('<int:behind_pk>/detail/', views.detail, name="detail"),
     path('<int:behind_pk>/delete/', views.delete, name="delete"),
     path('<int:behind_pk>/update/', views.update, name="update"),
     path('<int:behind_pk>/comment_create/', views.comment_create, name="comment_create"),
     path('<int:behind_pk>/comment_update/<int:comment_pk>/', views.comment_update, name="comment_update"),
     path('<int:behind_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
     path('<int:behind_pk>/likes/', views.likes, name="likes"),
]

pjt/behinds/templates/behinds/create.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/create-alert.js" %}"></script>
{% endblock script %}

{% block content %}
{% comment %} alert modal 부분 {% endcomment %}
  <div class="create-alert" id="create-alert">
    <div class="create-alert-modal">
      {% for message in messages %}
        <p class="alert-message">{{ message }}</p>
      {% endfor %}
    </div>
  </div>

  {% comment %} 감독 비하인드 작성 {% endcomment %}
  <div class="nav">감독 비하인드 작성 페이지</div>
  <hr>
  <div class="form-box">
    <form action="{% url 'behinds:create' %}" method="POST">
      {% csrf_token %}
      <div class="title">
        {% if flag %}
          <input type="text" name="title" id="title" value = "{{ beforeTitle }}">
        {% else %}
          <input type="text" name="title" id="title" placeholder = "제목을 입력하세요.">
        {% endif %}
      </div>
      <div class="content">
        {% if flag %}
          <textarea id="content" name="content" cols="30" rows="10">{{ beforeContent }}</textarea>
        {% else %}
          <textarea id="content" name="content" cols="30" rows="10" placeholder="내용을 입력하세요."></textarea>
        {% endif %}
      </div>
      <input type="submit" class="submit-btn" value="작성하기">
    </form>
  </div>
  <a href="{% url 'behinds:index' %}"><img src="{% static "images/back.png" %}" alt="" class="back"></a>
{% endblock content %}

pjt/behinds/templates/behinds/detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/detail.css" %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/edit.js" %}"></script>
  <script type="text/javascript" src="{% static "js/navbar-back.js" %}"></script>
{% endblock script %}

{% block content %}
  <a href="{% url 'behinds:index' %}" id="back-page"><img src="{% static "images/back.png" %}" alt="" class="back"></a>
  <div class="detail">
    <div class="detail-box">
      <div class="btn">
        <form action="{% url 'behinds:update' behind.pk %}" method="GET">
          <button type="subimt" class="margin-btn"><img src="{% static "images/pencil.png" %}" alt="" class="img"></button>
        </form>
        <form action="{% url 'behinds:delete' behind.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit"><img src="{% static "images/delete.png" %}" alt="" class="img"></button>
        </form>
      </div>
      <h1 class="behind-title">{{ behind.title }}</h1>
      <div class="info">
        <p>작성자 : <a href="{% url 'mypage:index' behind.user.pk %}" class="nickname1">{{ behind.user.username }}</a> 감독</p>
        <p>작성일자 : {{ behind.updated_at | date:"Y.m.d H:i:s" }}</p>
      </div>
      <hr>
      <p>{{ behind.content }}</p>
    </div>
    
    {% comment %} comment {% endcomment %}
    <div class="second-box">
      <p class="comment-info">댓글 작성</p>
      <form action="{% url 'behinds:comment_create' behind.pk %}"  method="POST" class="form">
        {% csrf_token %}
        {{ form.content }}
        {{ form.content.errors }}
        <button type="submit" class="comment-btn">등록</button>
      </form>

      <div class="comments">
        {% for comment in comments %}
          <div class="comment-box">
            <div class="comment-profile">
              <div>
                <a href="{% url 'mypage:index' comment.user_comment.pk %}" class="nickname">{{ comment.user_comment.nickname }}</a>
                <span class="nickname">{{ comment.updated_at | date:"Y.m.d H:i:s" }}</span>
              </div>
            
              <div class="btn2">
                {% if comment.user_comment == user %}
                  <form
                    class="update-form update-form{{ comment.pk }}"
                    data-comment-id="{{ comment.pk }}"
                    data-comment-content="{{ comment.content }}"
                    style="display:block;"
                  >
                    <button type="submit" class="update-btn">수정</button>
                  </form>
                  <form
                    class="udpate-form-axios update-form-axios{{ comment.pk }}"
                    data-comment-id="{{ comment.pk }}"
                    data-comment-content="{{ comment.content }}"
                    data-behind-id="{{ behind.pk }}"
                    style="display:none;"
                  >
                    <button type="submit" class="update-btn">수정</button>
                    <button
                      class="update-btn edit-cancel edit-cancel{{ comment.pk }}"
                      data-comment-id="{{ comment.pk }}"
                      data-comment-content="{{ comment.content }}"
                    >취소</button>
                  </form>
                  <form action="{% url 'behinds:comment_delete' behind.pk comment.pk %}">
                    <button type="submit" class="update-btn">삭제</button>
                  </form>
                {% endif %}
              </div>
            </div>
            <div id="edit-div{{ comment.pk }}" style="display:none;">
              <input type="text" id="edit-area{{ comment.pk }}" class="edit-input">
            </div>
            {% comment %} 댓글 나오는 부분 {% endcomment %}
            <div class="comment-scroll">
              <span id="comment-{{ comment.pk }}" class="comment-content">{{ comment.content }}</span>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

pjt/behinds/templates/behinds/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/behinds.css' %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/search.js" %}"></script>
  <script type="text/javascript" src="{% static "js/follow.js" %}"></script>
  <script type="text/javascript" src="{% static "js/like.js" %}"></script>
  <script type="text/javascript" src="{% static "js/sorted.js" %}"></script>
  <script type="text/javascript" src="{% static "js/modal.js" %}"></script>
{% endblock script %}

{% block content %}
  {% comment %} 검색하는 부분 {% endcomment %}
  <div class="modal-box not-visible" id="modal">
    <div class="modal">
      <form action="" method="post" class="modal-form">
        {% csrf_token %}
        <input type="text" class="input" id="search-input" data-behind-content="{{ behinds }}">
        <img src="{% static "images/search.png" %}" alt="" class="search">
      </form>
      <div id="result-Box" class="result-card not-visible"></div>
    </div>
  </div>
  {% comment %} 검색하는 부분 {% endcomment %}

  <div class="create-alert not-visible" id="create-alert">
    <div class="create-alert-modal">
      <p class="alert-font">글을 작성하시려면 감독 권한이 부여된 회원 정보로 로그인해주세요.</p>
      <button class="alert-btn" id="alert-btn">확인</button>
    </div>
  </div>
  
  <div class="nav">감독 비하인드</div>
  <hr>
  <div class="box">
    <div class="re-select-box">
      <span class="re-select" id="recent">최신순</span>
      <span class="re-select deactivate" id="popular">인기순</span>
      <span class="re-select search-box" id="search-btn">검색하기</span>
      <a href="{% url 'behinds:create' %}" data-user-auth="{{ user.behind_auth }}" class="create-page" id="create-page">글쓰기</a>
    </div>

    {% comment %} 최신순 {% endcomment %}
    <div class="middle-box" id="recent-form">
      <div class="form-box" id="form-box">
        {% if recentBehinds %}
          {% for behind in recentBehinds %}
            <div class="form-list" id="form-list">
              <div class="profile">
                <div class="profile-user">
                  {% if behind.user.profile_image %}
                    <img src="{{ behind.user.profile_image.url }}" alt="" class="user">
                  {% endif %}
                  <p id="director">{{ behind.user.username }} 감독</p>
                </div>
                <form id="follow-form" data-user-id="{{ behind.user.pk }}">
                  {% csrf_token %}
                  {% if user in behind.user.followers.all %}
                    <button type="submit" class="follow" id="like-button-{{ behind.user.pk }}">언팔로우</button>
                  {% else %}
                    <button type="submit" class="follow" id="like-button-{{ behind.user.pk }}">팔로우</button>
                  {% endif %}
                </form>
              </div>

              <div class="in-content-box">
                <a href="{% url 'behinds:detail' behind.pk %} " class="content-a"><h2>{{ behind.title }}</h2></a>    
                {% if behind.content|length > 300 %}
                  <p>{{ behind.content | slice:"301" }}...</p>
                {% else %}
                  <p>{{ behind.content | slice:"301" }}</p>
                {% endif %}

                <div class="like" data-behind-id="{{ behind.pk }}">
                  {% if user in behind.like_user.all %}
                    <img
                      src="{% static "images/heart.png" %}"
                      class="like-img like-img-button like-img-button-{{ behind.pk }}"
                      data-behind-id="{{ behind.pk }}"
                    >
                  {% else  %}
                    <img
                      src="{% static "images/love.png" %}"
                      class="like-img like-img-button like-img-button-{{ behind.pk }}"
                      data-behind-id="{{ behind.pk }}"
                    >
                  {% endif %}
                  <p id="like-count-{{ behind.pk }}">{{ behind.like_user.all|length }}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p style="color:#d9d9d9; margin-top:150px;">작성된 게시글이 없습니다.</p>
        {% endif %}
      </div>
    </div>

    {% comment %} 인기순 {% endcomment %}
    <div class="middle-box not-visible" id="popular-form">
      <div class="form-box" id="form-box">
        {% if popularBehinds %}
          {% for behind in popularBehinds %}
            <div class="form-list" id="form-list">
              <div class="profile">
                <div class="profile-user">
                  {% if behind.user.profile_image %}
                    <img src="{{ behind.user.profile_image.url }}" alt="" class="user">
                  {% endif %}
                  <p id="director">{{ behind.user.username }} 감독</p>
                </div>
                <form id="follow-form" data-user-id="{{ behind.user.pk }}">
                  {% csrf_token %}
                  {% if user in behind.user.followers.all %}
                    <button type="submit" class="follow" id="like-button-{{ behind.user.pk }}">언팔로우</button>
                  {% else %}
                    <button type="submit" class="follow" id="like-button-{{ behind.user.pk }}">팔로우</button>
                  {% endif %}
                </form>
              </div>

              <div class="in-content-box">
                <a href="{% url 'behinds:detail' behind.pk %} " ><h2>{{ behind.title }}</h2></a>
                {% if behind.content|length > 300 %}
                  <p>{{ behind.content | slice:"301" }}...</p>
                {% else %}
                  <p>{{ behind.content | slice:"301" }}</p>
                {% endif %}

                <div class="like" data-behind-id="{{ behind.pk }}">
                  {% if user in behind.like_user.all %}
                    <img
                      src="{% static "images/heart.png" %}"
                      class="like-img like-img-button like-img-button-{{ behind.pk }}"
                      data-behind-id="{{ behind.pk }}"
                    >
                  {% else  %}
                    <img
                      src="{% static "images/love.png" %}"
                      class="like-img like-img-button like-img-button-{{ behind.pk }}"
                      data-behind-id="{{ behind.pk }}"
                    >
                  {% endif %}
                  <p id="like-count-{{ behind.pk }}">{{ behind.like_user.all|length }}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p style="color:white; margin-top:150px;">작성된 게시글이 없습니다.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

pjt/behinds/templates/behinds/update.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/create-alert.js" %}"></script>
{% endblock script %}

{% block content %}
{% comment %} alert modal 부분 {% endcomment %}
  <div class="create-alert" id="create-alert">
    <div class="create-alert-modal">
      {% for message in messages %}
        <p class="alert-message">{{ message }}</p>
      {% endfor %}
    </div>
  </div>

  {% comment %} 감독 비하인드 수정 {% endcomment %}
  <div class="nav">감독 비하인드 수정 페이지</div>
  <div class="form-box">
    <form action="{% url 'behinds:update' behind.pk %}" method="POST">
      {% csrf_token %}
      <div class="title">
        <input type="text" name="title" id="title" value = "{{ behind.title }}">
      </div>
      <div class="content">
        <textarea id="content" name="content" cols="30" rows="10">{{ behind.content }}</textarea>
      </div>
      <input type="submit" class="submit-btn">
    </form>
  </div> 
  <a href="{% url 'behinds:detail' behind.pk %}"><img src="{% static "images/back.png" %}" alt=""></a>
{% endblock content %}