pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('signin/', views.signin, name="signin"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('<int:user_pk>/update/', views.update, name="update"),
    path('<int:user_pk>/delete/', views.delete, name="delete"),
    path('<int:user_pk>/follow/', views.follow, name="follow"),
]

pjt/accounts/templates/accounts/signin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "css/user-login.css" %}">
  <title>SIGNIN</title>
</head>
<body>
  {% comment %} error alert 띄우는 부분 {% endcomment %}
  <div class="login-alert" id="login-alert">
    <div class="login-alert-modal">
      {% for message in messages %}
        <p class="alert-message">{{ message }}</p>
      {% endfor %}
    </div>
  </div>

  {% comment %} 로그인하는 부분 {% endcomment %}
  <div class="signin">
    <div class="login-tag">
      <a href="{% url 'accounts:signup' %}" class="a active"><h1>SIGN UP</h1></a>
      <h1>|</h1>
      <a href="{% url 'accounts:signin' %}" class="a"><h1>SIGN IN</h1></a>
    </div>
    <form action="{% url 'accounts:signin' %}" method="POST">
      {% csrf_token %}
      <div class='input'>
        <label for="{{ form.username.id_for_label }}">Email / Username</label><br>
        {{ form.username }}
      </div>
      <div class="input margin">
        <label for="{{ form.password.id_for_label }}">Password</label><br>
        {{ form.password }}
      </div>
      <div class="submit">
        <input type="submit" class="submit-btn margin" value="SIGN IN">  
      </div>
    </form>
  </div>

  <script type="text/javascript" src="{% static "js/signin-alert.js" %}"></script>
</body>
</html>

pjt/accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/user-login.css' %}">
  <title>Document</title>
</head>
<body>
  {% comment %} error alert 띄우는 부분 {% endcomment %}
  <div class="login-alert" id="login-alert">
    <div class="login-alert-modal">
      {% for message in messages %}
        <p class="alert-message">{{ message }}</p>
      {% endfor %}
    </div>
  </div>

  {% comment %} 회원가입하는 부분 {% endcomment %}
  <div class="signup">
    <div class="login-tag">
      <a href="{% url 'accounts:signup' %}" class="a"><h1>SIGN UP</h1></a>
      <h1>|</h1>
      <a href="{% url 'accounts:signin' %}" class="a active"><h1>SIGN IN</h1></a>
    </div>
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% comment %} {{ form.as_p }} {% endcomment %}
      <div class="input">
        <label for="{{ form.username.id_for_label }}">Username</label><br>
        {{ form.username }}
      </div>
      <div class="input">
        <label for="{{ form.nickname.id_for_label }}">Nickname</label><br>
        {{ form.nickname }}
      </div>
      <div class="input">
        <label for="{{ form.email.id_for_label }}">Email</label><br>
        {{ form.email }}
      </div>
      <div class="input">
        <label for="{{ form.password1.id_for_label }}">Password</label><br>
        {{ form.password1 }}
      </div>
      <p class="check">감독 인증이 필요하신 분들은 _____@gmail.com으로<br> 필요한 서류를 제출하시길 바랍니다.</p>
      <div class="submit">
        <button type="submit" class="submit-btn">SIGN UP</button>
      </div>
    </form>
  </div>

  <script type="text/javascript" src="{% static "js/signup-alert.js" %}"></script>
</body>
</html>

pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/update.css" %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/accounts-navbar-back.js" %}"></script>
{% endblock script %}

{% block content %}
  {% comment %} update error alert 띄우는 부분 {% endcomment %}
  <div class="update-alert" id="update-alert">
    <div class="update-alert-modal">
      {% for message in messages %}
        <p class="alert-message">{{ message }}</p>
      {% endfor %}
    </div>
  </div>

  <div class="nav">회원 정보 수정</div>
  <hr>
  <div class="box">
    <div class="update-box">
      <form action="{% url 'accounts:update' user.pk %}"  method="POST" enctype="multipart/form-data" id="update-form">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <div class="middle">
          <div class="first">
            <h2>회원 정보 수정</h2>
            <div class="input">
              <label for="{{ form.username.id_for_label }}">Username</label><br>
              {{ form.username }}
              {{ form.username.errors }}
            </div>
            <div class="input">
              <label for="{{ form.nickname.id_for_label }}">Nickname</label><br>
              {{ form.nickname }}
              {{ form.nickname.errors }}
            </div>
            <div class="input">
              <label for="{{ form.email.id_for_label }}">Email</label><br>
              {{ form.email }}
              {{ form.email.errors }}
            </div>
          </div>
          {% comment %} {{ passwordForm.as_p }} {% endcomment %}
          <div class="first">
            <h2>비밀번호 수정</h2>
            <div class="input">
              <label for="{{ passwordForm.new_password1.id_for_label }}">New Password</label><br>
              {{ passwordForm.new_password1 }}
            </div>
            <div class="input">
              <label for="{{ passwordForm.new_password2.id_for_label }}">New Password2</label><br>
              {{ passwordForm.new_password2 }}
            </div>
            <div class="input" id="img-update">
              {% comment %} <label for="{{ form.email.id_for_label }}">Email</label><br> {% endcomment %}
              {{ form.profile_image }}
              {% comment %} {{ form.email.errors }} {% endcomment %}
            </div>
          </div>
        </div>
        <input type="submit" value="수정" class="submit-btn">
      </form>
    </div>
  </div>
  <div id="back-page">
    <a href="{% url 'mypage:index' user.pk %}"><img src="{% static "images/back.png" %}" alt="" class="back"></a>
  </div>

  <script type="text/javascript" src="{% static "js/update-alert.js" %}"></script>
{% endblock content %}