pjt/mypage/urls.py
from django.urls import path
from . import views

app_name = "mypage"

urlpatterns = [
    path('<int:user_pk>/profile/', views.index, name="index"),
    path('<int:user_pk>/likedirectors/', views.likedirectors, name="likedirectors"),
    path('<int:user_pk>/likemovies/', views.likemovies, name="likemovies"),
]

pjt/mypage/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import get_user_model

from django.http import JsonResponse

import json

# Create your views here.

def index(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        'person': person,
    }
    return render(request, 'mypage/index.html', context)

def likedirectors(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    directors = person.followings.all()
    context = {
        'person' : person,
        'directors': directors
    }
    return render(request, 'mypage/likedirectors.html', context)

def likemovies(request, user_pk):
    if request.body:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        movies = person.votemovie_set.all()
        jsonObject = json.loads(request.body)
        stars = jsonObject.get('stars')
        starList = float(jsonObject.get('starList'))
        starsList = jsonObject.get('starsList')
        returnlist = 0
        status = ''
        moviesstarlist = movies.filter(vote=stars).count()
        if moviesstarlist / 5 <= starList :
            returnlist = moviesstarlist // 5
            status = 'over'
        else:
            status = 'none'
            returnlist = starList

        moviesanystar = movies.filter(vote=stars)[5*returnlist:5*(returnlist+1)]
        jsonContext = []
        for movie in moviesanystar:
            jsonContext.append({
                'pk': movie.like_movies.pk,
                'poster_url': movie.like_movies.poster_path,
                'title': movie.like_movies.title,
                'status': status,
                'returnstarlist': starsList
            })
        return JsonResponse(jsonContext, safe=False)
    else:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        movies = person.votemovie_set.all()
        movies5star = movies.filter(vote=5)[0:5]
        movies4star = movies.filter(vote=4)[0:5]
        movies3star = movies.filter(vote=3)[0:5]
        movies2star = movies.filter(vote=2)[0:5]
        movies1star = movies.filter(vote=1)[0:5]
        context = {
            'person': person,
            'movies5star': movies5star,
            'movies4star': movies4star,
            'movies3star': movies3star,
            'movies2star': movies2star,
            'movies1star': movies1star,
        }
        return render(request, 'mypage/likemovies.html', context)

pjt/mypage/templates/mypage/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/mypage.css" %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/quit.js" %}"></script>
{% endblock script %}

{% block content %}
  <div class="quit-alert not-visible" id="quit-alert">
    <div class="quit-alert-modal">
      <p class="alert-font">정말로 탈퇴하시겠습니까 ?</p>
      <div class="quit-btns">
        <form action="{% url 'accounts:delete' person.pk %}" method="POST">
          {% csrf_token %}
          <button class="quit-btn" id="quit-btn">예</button>
        </form>
        <button class="quit-btn" id="cancel">아니오</button>
      </div>
    </div>
  </div>

  <div class="nav">{{ person.nickname }} 님의 공간</div>
  <hr class="main-hr">
  <div class="box">
    {% if person.profile_image %}
      <img src="{{ person.profile_image.url }}" alt="profile" class="user-img">
    {% endif %}
    <div class="profile"> 
      <h2>{{ person.username }}</h2>
      <h3>{{ person.nickname }}</h3>
      <br>
      <div class="go-page">
        <p>팔로우한 감독</p>
        <button onclick="location.href=`{% url 'mypage:likedirectors' person.pk %}`" class="btn">GO</button>
      </div>
      <hr class="hr" align="left">
      <div class="go-page">
        <p>별점 남긴 영화</p>
        <button onclick="location.href=`{% url 'mypage:likemovies' person.pk %}`" class="btn">GO</button>
      </div>
      {% if user.username == person.username %}
        <hr class="hr" align="left">
        <div class="go-page">
          <p>회원 정보 수정</p>
          <form action="{% url 'accounts:update' person.pk %}" method="GET">
            <button type="submit" class="btn">GO</button>
          </form>
        </div>
        <hr class="hr" align="left">
        <div class="go-page">
          <p>회원 탈퇴</p>
          <form action="{% url 'accounts:delete' person.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn" id="quit-account">GO</button>
          </form>
        </div>
        {% endif %}
      <hr class="hr" align="left">
    </div>
  </div>

{% endblock content %}

pjt/mypage/templates/mypage/likedirectors.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/likedirectors.css" %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/navbar-back.js" %}"></script>
{% endblock script %}

{% block content %}
  <div class="nav">{{ person.nickname }} 님이 팔로우한 감독</div>
  <hr>
  <div class="box-align">
    <div class="back-page" id="back-page">
      <a href="http://127.0.0.1:8000/mypage/{{person.pk}}/profile"><img src="{% static "images/back.png" %}" alt="" class="back"></a>
    </div>
    <div class="box">
      {% if directors %}
        {% for director in directors %}
          <div class="director-box">
            <div class="director-profile">
              {% if director.profile_image %}
                <img src="{{ director.profile_image.url }}" alt="" class="director-img">
              {% endif %}
              <p>{{ director }} 감독</p>
            </div>
            <p>최근 게시글</p>
            {% if director.behind_set.all.last.title|length > 30 %}
              <a href="http://127.0.0.1:8000/behinds/{{ director.behind_set.all.last.pk }}/detail/">{{ director.behind_set.all.last.title | slice:"31" }} ...</a>
            {% else %}
              <a href="http://127.0.0.1:8000/behinds/{{ director.behind_set.all.last.pk }}/detail/">{{ director.behind_set.all.last.title }}</a>
            {% endif %}
          </div>
        {% endfor %}
      {% else %}
        <p style="color:#d9d9d9; margin-top:150px; margin-left: 500px;">팔로우한 감독이 없습니다.</p>
      {% endif %}
    </div>
  </div>
{% endblock content %}

pjt/mypage/templates/mypage/likemovies.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/likemovies.css" %}">
{% endblock css %}

{% block script %}
  <script type="text/javascript" src="{% static "js/list.js" %}"></script>
  <script type="text/javascript" src="{% static "js/navbar-back.js" %}"></script>
{% endblock script %}

{% block content %}
  <div class="nav">{{ person.nickname }} 님이 별점 남긴 영화</div>
  <hr>
  {% comment %} 유저 프로필로 돌아가기 {% endcomment %}
  <div class="box-align">
    <div class="back-page" id="back-page">
      <a href="{% url 'mypage:index' person.pk %}"><img src="{% static "images/back.png" %}" alt="" class="back"></a>
    </div>
    <div class="movie-box">
      <div class="box">
        {% if not movies5star and not movies4star and not movies3star and not movies2star and not movies1star %}
          <p style="color:#d9d9d9; margin-left:650px;">별점을 남긴 영화가 없습니다.</p>
        {% endif %}
        {% comment %} 별점 5점인 영화 {% endcomment %}
        {% if movies5star %}
          <div class="movie-list">
            <div class="stars">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
            </div>
            <div class="page-btn">
              <form action="" id="star5-form" data-user-id="{{ user.pk }}" data-stars="5" data-stars-list="fiveList">
                {% csrf_token %}
                <input TYPE="IMAGE" src="{% static "images/before.png" %}" name="Submit" value="before" class="before" id="before" align="absmiddle">
                <input TYPE="IMAGE" src="{% static "images/next.png" %}" name="Submit" value="next" class="next" id="next" align="absmiddle">
              </form>
            </div>
            <div class="img-list" id="img-list-star5">
              {% for movie5star in movies5star %}
                <a href="{% url 'movies:detail' movie5star.like_movies.pk %}">
                  <img src="https://image.tmdb.org/t/p/w500{{ movie5star.like_movies.poster_path }}" alt="movie img" class="movie-img">
                </a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
      <div class="box">
        {% comment %} 별점 4점인 영화 {% endcomment %}
        {% if movies4star %}
          <div class="movie-list">
            <div class="stars">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
            </div>
            <div class="page-btn">
              <form action="" id="star4-form" data-user-id="{{ user.pk }}" data-stars="4" data-stars-list="fourList">
                {% csrf_token %}
                <input TYPE="IMAGE" src="{% static "images/before.png" %}" name="Submit" value="before" class="before" id="before" align="absmiddle">
                <input TYPE="IMAGE" src="{% static "images/next.png" %}" name="Submit" value="next" class="next" id="next" align="absmiddle">
              </form>
            </div>
            <div class="img-list" id="img-list-star4">
              {% for movie4star in movies4star %}
                <a href="{% url 'movies:detail' movie4star.like_movies.pk %}">
                  <img src="https://image.tmdb.org/t/p/w500{{ movie4star.like_movies.poster_path }}" alt="movie img" class="movie-img">
                </a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
      <div class="box">
        {% comment %} 별점 3점인 영화 {% endcomment %}
        {% if movies3star %}
          <div class="movie-list">
            <div class="stars">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
            </div>
            <div class="page-btn">
              <form action="" id="star3-form" data-user-id="{{ user.pk }}" data-stars="3" data-stars-list="threeList">
                {% csrf_token %}
                <input TYPE="IMAGE" src="{% static "images/before.png" %}" name="Submit" value="before" class="before" id="before" align="absmiddle">
                <input TYPE="IMAGE" src="{% static "images/next.png" %}" name="Submit" value="next" class="next" id="next" align="absmiddle">
              </form>
            </div>
            <div class="img-list" id="img-list-star3">
              {% for movie3star in movies3star %}
                <a href="{% url 'movies:detail' movie3star.like_movies.pk %}">
                  <img src="https://image.tmdb.org/t/p/w500{{ movie3star.like_movies.poster_path }}" alt="movie img" class="movie-img">
                </a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
      <div class="box">
        {% comment %} 별점 2점인 영화 {% endcomment %}
        {% if movies2star %}
          <div class="movie-list">
            <div class="stars">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
            </div>
            <div class="page-btn">
              <form action="" id="star2-form" data-user-id="{{ user.pk }}" data-stars="2" data-stars-list="twoList">
                {% csrf_token %}
                <input TYPE="IMAGE" src="{% static "images/before.png" %}" name="Submit" value="before" class="before" id="before" align="absmiddle">
                <input TYPE="IMAGE" src="{% static "images/next.png" %}" name="Submit" value="next" class="next" id="next" align="absmiddle">
              </form>
            </div>
            <div class="img-list" id="img-list-star2">
              {% for movie2star in movies2star %}
                <a href="{% url 'movies:detail' movie2star.like_movies.pk %}">
                  <img src="https://image.tmdb.org/t/p/w500{{ movie2star.like_movies.poster_path }}" alt="movie img" class="movie-img">
                </a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
      <div class="box">
        {% comment %} 별점 1점인 영화 {% endcomment %}
        {% if movies1star %}
          <div class="movie-list">
            <div class="stars">
              <img src="{% static "images/star.png" %}" alt="" class="star-img">
            </div>
            <div class="page-btn">
              <form action="" id="star1-form" data-user-id="{{ user.pk }}" data-stars="1" data-stars-list="oneList">
                {% csrf_token %}
                <input TYPE="IMAGE" src="{% static "images/before.png" %}" name="Submit" value="before" class="before" id="before" align="absmiddle">
                <input TYPE="IMAGE" src="{% static "images/next.png" %}" name="Submit" value="next" class="next" id="next" align="absmiddle">
              </form>
            </div>
            <div class="img-list" id="img-list-star1">
              {% for movie1star in movies1star %}
                <a href="{% url 'movies:detail' movie1star.like_movies.pk %}">
                  <img src="https://image.tmdb.org/t/p/w500{{ movie1star.like_movies.poster_path }}" alt="movie img" class="movie-img">
                </a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
    
{% endblock content %}